// This file is autogenerated.
module.exports = {
  v_init_pars: require('./lib/chunks/init_pars.vert'),
  v_normal_pars: require('./lib/chunks/normal_pars.vert'),
  v_normal: require('./lib/chunks/normal.vert'),
  f_color: require('./lib/chunks/color.frag'),
  f_init_pars: require('./lib/chunks/init_pars.frag'),
  f_init: require('./lib/chunks/init.frag'),
  f_lambert_light_pars: require('./lib/chunks/lambert_light_pars.frag'),
  f_lambert_light: require('./lib/chunks/lambert_light.frag'),
  f_lights: require('./lib/chunks/lights.frag'),
  f_normal_pars: require('./lib/chunks/normal_pars.frag'),
  f_normal: require('./lib/chunks/normal.frag')
};
