import fs from 'fs';
import gulp from 'gulp';
import glob from 'glob';
import watch from 'gulp-watch';

gulp.task('build-shader-chunks', () => {
  fs.writeFile('./src/shaders/chunks.js',
    `// This file is autogenerated.
module.exports = {
${
  glob.sync('./src/shaders/lib/chunks/**/*.vert')
    .map(filename => filename.replace(/.*(lib\/chunks(.*)\/([aA-zZ]*)\..*)/, '  v_$3: require(\'./$1\'),'))
    .join('\n')
}
${
  glob.sync('./src/shaders/lib/chunks/**/*.frag')
    .map(filename => filename.replace(/.*(lib\/chunks(.*)\/([aA-zZ]*)\..*)/, '  f_$3: require(\'./$1\'),'))
    .join('\n').slice(0, -1)
}
};
`,
    () => {
      console.log('build-shader-chunks: done!');
    }
  );
});

gulp.task('watch-shader-chunks', () => {
  const watcher = watch('./src/shaders/lib/chunks/**/*.{frag,vert}');

  watcher.on('add', () => gulp.start('build-shader-chunks'));
  watcher.on('unlink', () => gulp.start('build-shader-chunks'));
});
